version: "2"
services:
    app:
        container_name: StreamApp
        restart: always
        build: .
        ports:
            - "80:80"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
volumes:
  mongodata:
            
            